version: '3.8'
services:
  influxdb3-core:
    image: influxdb/influxdb3-core:latest
    container_name: influxdb3-core
    ports:
      - "8181:8181"
    volumes:
      - influxdb3_data:/var/lib/influxdb3
    environment:
      - INFLUXDB_DATABASE=sensores
      - INFLUXDB_HOST=0.0.0.0
      - INFLUXDB_PORT=8181
      - INFLUXDB_TOKEN=meu-token-super-secreto
    command: >
      sh -c "influxdb3 serve 
             --host 0.0.0.0 
             --port 8181 
             --object-store file 
             --data-dir /var/lib/influxdb3 
             --database-directory /var/lib/influxdb3/db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8181/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      influxdb3-core:
        condition: service_healthy

volumes:
  influxdb3_data:
    driver: local
  grafana_data:
    driver: local