version: '3.8'
services:
  influxdb3-core:
    image: influxdb:3.3-core
    container_name: influxdb3-core
    ports:
      - "8181:8181"
    volumes:
      - influxdb3_data:/var/lib/influxdb3
    environment:
      - INFLUXDB3_DATA_DIR=/home/influxdb3/.influxdb3
      - INFLUXDB_IOX_DB_DIR=/var/lib/influxdb3
      - LOG_FILTER=info
      - INFLUXDB_TOKEN=meu-token-super-secreto
    command: >
      influxdb3 serve 
      --object-store file
      --data-dir /var/lib/influxdb3
      --node-id node1

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  influxdb3_data:
    driver: local
  grafana_data:
    driver: local