version: '3'
services:
  influxdb:
    image: influxdb:3.1.1
    container_name: influxdb_v3
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data_v3:/var/lib/influxdb  # Recomendável usar um novo diretório para os dados da v3
    environment:
      - INFLUXDB_DB=sensores
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin12345
      - INFLUXDB_ADMIN_TOKEN=meu-token-super-secreto
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data:
    driver: local