version: '3.7'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb_v3_sensores
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_v3_data:/var/lib/influxdb2
    environment:
      - INFLUXDB_DB=sensores
      - INFLUXDB_ORG=minha-org
      - INFLUXDB_ADMIN_TOKEN=meu-token-super-secreto
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data:
    driver: local