version: '3.8'
services:
  influxdb3-core:
    image: influxdb:3-core
    container_name: influxdb3-core
    ports:
      - "8181:8181"    
    volumes:
      - influxdb3_data:/var/lib/influxdb3
    environment:
      - INFLUXDB3_DATA_DIR=/home/influxdb3/.influxdb3
      - INFLUXDB_IOX_DB_DIR=/var/lib/influxdb3
      - LOG_FILTER=info
    command: >
      influxdb3 serve 
      --object-store file
      --data-dir /var/lib/influxdb3
      --node-id node1

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=false
    depends_on:
      - influxdb3-core

volumes:
  influxdb3_data:
    driver: local
  grafana_data:
    driver: local