version: '3.7'

services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb_sensores
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin      
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345 
      - DOCKER_INFLUXDB_INIT_ORG=minha-org       
      - DOCKER_INFLUXDB_INIT_BUCKET=sensores     
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=meu-token-super-secreto
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data:
    driver: local